### PR TITLE
Js_browser: get location from window

### PR DESCRIPTION
**Pull request by pveber**

### CODE REVIEW

**Comment by pveber** [comment]
Any chance to have that patch included?

**Comment by alainfrisch** [comment]
Yes, absolutely!  Sorry for the slow reaction, I just need to find some time to review/test.  I should also find a way to create some automated unit tests (with a headless browser).

**Comment by pveber** [comment]
Great! Let me know if I can do something to help.

**Comment by alainfrisch** [comment]
Thanks for the contribution!

**Pull request merged**
